#!/bin/bash

# Photo-SLAM Project Help
# Usage: ./help.sh

echo "Photo-SLAM Project Help"
echo "======================"
echo ""

echo "Project Structure:"
echo "  PhotoSLAM/          - Original Photo-SLAM implementation"
echo "  PhotoSLAM_RTGS/     - Photo-SLAM with RTGS enhancements"
echo "  run_original.sh     - Script to run original Photo-SLAM"
echo "  run_rtgs.sh         - Script to run Photo-SLAM with RTGS"
echo "  build_all.sh        - Build both versions"
echo "  download_datasets.sh - Download all datasets"
echo "  help.sh             - This help file"
echo ""

echo "Quick Start:"
echo "============"
echo "1. Build both versions:"
echo "   ./build_all.sh"
echo ""
echo "2. Download datasets (optional):"
echo "   ./download_datasets.sh"
echo ""
echo "3. Run experiments:"
echo "   ./run_original.sh [dataset_type] [scene_name] [dataset_path] [results_path]"
echo "   ./run_rtgs.sh [dataset_type] [scene_name] [dataset_path] [results_path]"
echo ""

echo "Dataset Types:"
echo "=============="
echo "  mono    - Monocular camera datasets"
echo "  rgbd    - RGB-D camera datasets"
echo "  stereo  - Stereo camera datasets"
echo ""

echo "Supported Scenes:"
echo "================="
echo "TUM RGB-D Dataset:"
echo "  - tum_freiburg1_desk"
echo "  - tum_freiburg2_xyz"
echo "  - tum_freiburg3_long_office_household"
echo ""
echo "Replica Dataset:"
echo "  - office0, office1, office2"
echo "  - room0, room1, room2"
echo "  - apartment0, apartment1, apartment2"
echo ""
echo "EuRoC Dataset:"
echo "  - EuRoC (includes all sequences)"
echo ""

echo "Usage Examples:"
echo "==============="
echo ""
echo "Original Photo-SLAM:"
echo "  ./run_original.sh rgbd tum_freiburg1_desk /path/to/tum/dataset /path/to/results"
echo "  ./run_original.sh rgbd office0 /path/to/replica/dataset /path/to/results"
echo "  ./run_original.sh stereo EuRoC /path/to/euroc/dataset /path/to/results"
echo ""
echo "RTGS Photo-SLAM:"
echo "  ./run_rtgs.sh rgbd tum_freiburg1_desk /path/to/tum/dataset /path/to/results"
echo "  ./run_rtgs.sh rgbd office0 /path/to/replica/dataset /path/to/results"
echo "  ./run_rtgs.sh stereo EuRoC /path/to/euroc/dataset /path/to/results"
echo ""
echo "Evaluation (disable viewer):"
echo "  ./run_original.sh rgbd tum_freiburg1_desk /path/to/tum/dataset /path/to/results no_viewer"
echo "  ./run_rtgs.sh rgbd office0 /path/to/replica/dataset /path/to/results no_viewer"
echo ""

echo "Dataset Paths:"
echo "=============="
echo "After downloading datasets with ./download_datasets.sh:"
echo "  TUM: ./PhotoSLAM/datasets/TUM/"
echo "  Replica: ./PhotoSLAM/datasets/Replica/"
echo "  EuRoC: ./PhotoSLAM/datasets/EuRoC/"
echo ""

echo "Troubleshooting:"
echo "==============="
echo "1. If executables not found:"
echo "   ./build_all.sh"
echo ""
echo "2. If config files not found:"
echo "   Check that the scene name matches exactly"
echo ""
echo "3. If dataset path not found:"
echo "   ./download_datasets.sh"
echo "   or specify the correct path to your dataset"
echo ""

echo "For more information, see README.md" 